accounts:
  - name: alice
    coins: ["120000000000uc4e"]
    mnemonic: "cabin gun luggage green fever either engage nest arrow sure record physical palace dutch clap vocal north snack birth exhibit either ancient sniff settle"
  - name: bob
    coins: ["4000000000uc4e"]
    mnemonic: "genuine author egg good melt obey omit antique flight fade midnight funny security budget inquiry animal unfold film soft midnight company rack kitchen monitor"
  - name: vesting_pools_owner
    coins: ["15000000uc4e"]
    mnemonic: "radar there legend edge jar across night figure dog oval clump endorse garage office upon square worth harvest twelve trust menu mother gossip simple"
  - name: validators_pool_owner
    coins: ["15000000uc4e"]
    mnemonic: "forget mesh pet uphold prison daughter surround drop fire surface nurse swing long black hockey hover bulb reform female prefer aim ten category rhythm"
validator:
  name: alice
  staked: "100000000uc4e"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000uc4e"]
init:
  home: "./.data"
  config:
    log_level: "debug"
    log_format: "plain"
genesis:
  app_state:
    auth:
      accounts:
        - @type: "/cosmos.auth.v1beta1.ModuleAccount"
          base_account:
            account_number: "9"
            address: "c4e1yl6hdjhmkf37639730gffanpzndzdpmhd80ywa"
            pub_key: null
            sequence: "0"
          name: "transfer"
          permissions:
            - minter
            - burner
        - @type: "/cosmos.vesting.v1beta1.ContinuousVestingAccount"
          base_vesting_account:
            base_account:
              account_number: "11"
              address: "c4e1xe3x4w0ma4dv805q0rhe0c7xk3mv24vatg7pm3"
              # mnemonic: pyramid jump crumble supply fall april more inner jacket news clutch sustain century vendor observe carpet coach early grief very beauty solution orphan cattle
              pub_key: null
              sequence: "0"
            delegated_free:
            delegated_vesting:
            end_time: "1770000000"
            original_vesting:
              - amount: "5000000000000"
                denom: "uc4e"
          start_time: "1670429736"
    bank:
      denom_metadata:
        - description: "Chain4Energy Token"
          denom_units:
            - denom: "uc4e"
              exponent: 0
              aliases:
                - microc4e
            - denom: "c4e"
              exponent: 6
          base: "uc4e"
          display: "c4e"
          name: "Chain4Energy Coin"
          symbol: "C4E"
      balances:
        # cfevesting module account
        - address: "c4e17yryahw88nkwsaphuywhv7ap8ty7zwgunjsple"
          coins:
            - denom: "uc4e"
              amount: "32500000000000"
        - address: "c4e1xe3x4w0ma4dv805q0rhe0c7xk3mv24vatg7pm3"
          coins:
            - denom: "uc4e"
              amount: "5000100000000"
    staking:
      params:
        bond_denom: "uc4e"
        unbonding_time: "100s"
    cfevesting:
      params:
        denom: "uc4e"
      vesting_types:
        - name: "Short vesting with lockup"
          lockup_period: 1
          lockup_period_unit: "minute"
          vesting_period: 10
          vesting_period_unit: "minute"
          token_releasing_period: 30
          token_releasing_period_unit: "second"
          delegations_allowed: false
        - name: "Mid vesting with lockup"
          lockup_period: 150
          lockup_period_unit: "minute"
          vesting_period: 150
          vesting_period_unit: "hour"
          token_releasing_period: 5
          token_releasing_period_unit: "minute"
          delegations_allowed: false
        - name: "Long vesting with lockup"
          lockup_period: 600
          lockup_period_unit: "hour"
          vesting_period: 70
          vesting_period_unit: "day"
          token_releasing_period: 10
          token_releasing_period_unit: "minute"
          delegations_allowed: false
        - name: "Mid vesting delegable"
          lockup_period: 0
          lockup_period_unit: "minute"
          vesting_period: 200
          vesting_period_unit: "hour"
          token_releasing_period: 5
          token_releasing_period_unit: "minute"
          delegations_allowed: true
        - name: "Long vesting delegable"
          lockup_period: 0
          lockup_period_unit: "minute"
          vesting_period: 100
          vesting_period_unit: "day"
          token_releasing_period: 10
          token_releasing_period_unit: "minute"
          delegations_allowed: true
        - name: "Advisors pool"
          lockup_period: 5
          lockup_period_unit: "minute"
          vesting_period: 5
          vesting_period_unit: "day"
          token_releasing_period: 10
          token_releasing_period_unit: "minute"
          delegations_allowed: false
        - name: "Validators pool"
          lockup_period: 10
          lockup_period_unit: "minute"
          vesting_period: 10
          vesting_period_unit: "day"
          token_releasing_period: 10
          token_releasing_period_unit: "minute"
          delegations_allowed: false
      account_vestings_list:
        vestings:
          - address: "c4e1lt5npfrl4fnvkxm387d8fc59x3vwugagm4vnzm"
            delegable_address: ""
            vestings:
              - id: 1
                delegation_allowed: false
                last_modification: "2022-03-30T00:00:00.00000000Z"
                last_modification_vested: "15000000000000"
                last_modification_withdrawn: "0"
                lock_end: "2025-03-30T00:00:00.00000000Z"
                release_period: "300s"
                sent: "0"
                vested: "15000000000000"
                vesting_end: "2025-03-30T00:00:00.00000000Z"
                vesting_start: "2022-03-30T00:00:00.00000000Z"
                vesting_type: "Advisors pool"
                withdrawn: "0"
                transfer_allowed: true
          # - address: "c4e14z9cdze48aygze82e42a29h5gg5z3vda0qx5wc"
          #   delegable_address: ""
          #   vestings:
              - id: 2
                delegation_allowed: false
                last_modification: "2022-03-30T00:00:00.00000000Z"
                last_modification_vested: "17500000000000"
                last_modification_withdrawn: "0"
                lock_end: "2024-03-30T00:00:00.00000000Z"
                release_period: "300s"
                sent: "0"
                vested: "17500000000000"
                vesting_end: "2024-03-30T00:00:00.00000000Z"
                vesting_start: "2022-03-30T00:00:00.00000000Z"
                vesting_type: "Validators pool"
                withdrawn: "0"
                transfer_allowed: true

    # genutil:
    #   gen_txs:
    #     messages:
    #       value:
    #         denom: "c4e",
