accounts:
  - name: alice
    coins: ["120000000000uc4e"]
    mnemonic: "cabin gun luggage green fever either engage nest arrow sure record physical palace dutch clap vocal north snack birth exhibit either ancient sniff settle"
  - name: bob
    coins: ["4000000000uc4e"]
    mnemonic: "genuine author egg good melt obey omit antique flight fade midnight funny security budget inquiry animal unfold film soft midnight company rack kitchen monitor"
  - name: vesting_pools_owner
    coins: ["15000000000000uc4e"]
    mnemonic: "radar there legend edge jar across night figure dog oval clump endorse garage office upon square worth harvest twelve trust menu mother gossip simple"
  - name: validators_pool_owner
    coins: ["15000000uc4e"]
    mnemonic: "forget mesh pet uphold prison daughter surround drop fire surface nurse swing long black hockey hover bulb reform female prefer aim ten category rhythm"
validator:
  name: alice
  staked: "100000000uc4e"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000uc4e"]
init:
  home: "./.data"
  app:
    telemetry:
      enabled: true
      prometheus-retention-time: 60

  #      enable-hostname-label: true
#      enable-hostname: true
  config:
    log_level: "debug"
    log_format: "plain"
    metrics:
      prometheusEnabledz
    instrumentation:
      prometheus: true
genesis:
  app_state:
    auth:
      accounts:
        - @type: "/cosmos.auth.v1beta1.ModuleAccount"
          base_account:
            account_number: "9"
            address: "c4e1yl6hdjhmkf37639730gffanpzndzdpmhd80ywa"
            pub_key: null
            sequence: "0"
          name: "transfer"
          permissions:
            - minter
            - burner
        - @type: "/cosmos.vesting.v1beta1.ContinuousVestingAccount"
          base_vesting_account:
            base_account:
              account_number: "11"
              address: "c4e1xe3x4w0ma4dv805q0rhe0c7xk3mv24vatg7pm3"
              # mnemonic: pyramid jump crumble supply fall april more inner jacket news clutch sustain century vendor observe carpet coach early grief very beauty solution orphan cattle
              pub_key: null
              sequence: "0"
            delegated_free:
            delegated_vesting:
            end_time: "1770000000"
            original_vesting:
              - amount: "5000000000000"
                denom: "uc4e"
          start_time: "1670429736"

    bank:
      denom_metadata:
        - description: "Chain4Energy Token"
          denom_units:
            - denom: "uc4e"
              exponent: 0
              aliases:
                - microc4e
            - denom: "c4e"
              exponent: 6
          base: "uc4e"
          display: "c4e"
          name: "Chain4Energy Coin"
          symbol: "C4E"
      balances:
        # cfevesting module account
        - address: "c4e17yryahw88nkwsaphuywhv7ap8ty7zwgunjsple"
          coins:
            - denom: "uc4e"
              amount: "32500000000000"
        - address: "c4e1xe3x4w0ma4dv805q0rhe0c7xk3mv24vatg7pm3"
          coins:
            - denom: "uc4e"
              amount: "5000100000000"
    staking:
      params:
        bond_denom: "uc4e"
        unbonding_time: "100s"

    gov:
      deposit_params:
        max_deposit_period: "50s"
        min_deposit:
          - denom: "uc4e"
            amount: "10000000"
      voting_params:
        voting_period: "10s"

    cfeminter:
      params:
        mint_denom: "uc4e"
        minter:
          start: "2022-07-05T00:00:00.00000000Z"
          periods:
            - position: 1
              type: "PERIODIC_REDUCTION_MINTER"
              periodic_reduction_minter:
                mint_period: 31536000 # year - 365*24*3600
                mint_amount: "40000000000000"
                reduction_period_length: 4
                reduction_factor: "0.5"
            # - position: 1
            #   period_end: "2024-03-30T00:00:00.00000000Z"
            #   type: "TIME_LINEAR_MINTER"
            #   time_linear_minter:
            #     amount: "40000000000000"
            # - position: 2
            #   type: "NO_MINTING"

      minter_state:
        position: 1
        amount_minted: "0"
    cfedistributor:
      params:
        sub_distributors:
        - name: tx_fee_distributor
          sources:
            - id: fee_collector
              type: MODULE_ACCOUNT
          destination:
            account:
              id: "c4e_distributor"
              type: MAIN
            burn_share:
              percent: "0"

        - name: inflation_and_fee_distributor
          sources:
            - id: c4e_distributor
              type: MAIN
          destination:
            account:
              id: "validators_rewards_collector"
              type: MODULE_ACCOUNT
            burn_share:
              percent: "5"
            share:
              - name: development_fund
                percent: "5"
                account:
                  #Proper development fund account
                  id: "c4e10ep2sxpf2kj6j26w7f4uuafedkuf9sf9xqq3sl"
                  type: BASE_ACCOUNT
              - name: usage_incentives
                percent: "35"
                account:
                  id: "usage_incentives_collector"
                  type: INTERNAL_ACCOUNT
        - name: usage_incentives_distributor
          sources:
            - id: usage_incentives_collector
              type: INTERNAL_ACCOUNT
          destination:
            burn_share:
              percent: "0"
            account:
              #LP Providers proper address
              id: "c4e1q5vgy0r3w9q4cclucr2kl8nwmfe2mgr6g0jlph"
              type: BASE_ACCOUNT
            share:
              - name: green_energy_booster
                percent: "34"
                account:
                  id: "green_energy_booster_collector"
                  type: MODULE_ACCOUNT
              - name: governance_booster
                percent: "33"
                account:
                  id: "governance_booster_collector"
                  type: MODULE_ACCOUNT


    cfevesting:
      params:
        denom: "uc4e"
      vesting_types:
        - name: "Short vesting with lockup"
          lockup_period: 1
          lockup_period_unit: "minute"
          vesting_period: 10
          vesting_period_unit: "minute"
        - name: "Mid vesting with lockup"
          lockup_period: 150
          lockup_period_unit: "minute"
          vesting_period: 150
          vesting_period_unit: "hour"
        - name: "Long vesting with lockup"
          lockup_period: 600
          lockup_period_unit: "hour"
          vesting_period: 70
          vesting_period_unit: "day"
        - name: "Mid vesting delegable"
          lockup_period: 0
          lockup_period_unit: "minute"
          vesting_period: 200
          vesting_period_unit: "hour"
        - name: "Long vesting delegable"
          lockup_period: 0
          lockup_period_unit: "minute"
          vesting_period: 100
          vesting_period_unit: "day"
        - name: "Advisors pool"
          lockup_period: 5
          lockup_period_unit: "minute"
          vesting_period: 5
          vesting_period_unit: "day"
        - name: "Validators pool"
          lockup_period: 10
          lockup_period_unit: "minute"
          vesting_period: 10
          vesting_period_unit: "day"
      account_vesting_pools:
        - address: "c4e1lt5npfrl4fnvkxm387d8fc59x3vwugagm4vnzm"
          # delegable_address: ""
          vesting_pools:
            - name: "Advisors pool"
              sent: "0"
              initially_locked: "15000000000000"
              lock_end: "2025-03-30T00:00:00.00000000Z"
              lock_start: "2022-03-30T00:00:00.00000000Z"
              vesting_type: "Advisors pool"
              withdrawn: "0"
            - name: "Validators pool"
              sent: "0"
              initially_locked: "17500000000000"
              lock_end: "2024-03-30T00:00:00.00000000Z"
              lock_start: "2022-03-30T00:00:00.00000000Z"
              vesting_type: "Validators pool"
              withdrawn: "0"

    # genutil:
    #   gen_txs:
    #     messages:
    #       value:
    #         denom: "c4e",
